### ISSUE TITLE
404s for toxics and reset

### ISSUE THREAD

**Issue by gaorlov** [Shopify/toxiproxy#106]
I set up Toxiproxy(1.2.1 from the .deb) with 3 servers. When i go to `http://localhost:8474/proxies` or do `Toxiproxy.all` I get results back, but when I try to examine the toxics for any of the servers, it 404s. Same with `Toxiproxy.reset`. Surely there's something simple I'm missing.

Individual proxies work as well. `Toxiproxy[:my_service]` works fine. It's `Toxiproxy[:my_service].toxics` that 404s

**Comment by Sirupsen** [comment]
Any reason you can't upgrade to Toxiproxy 2.0?

**Comment by gaorlov** [comment]
I knew there was something simple! Haha. What's the download path to the deb? The docs point at 1.2, which is the reason I'm using it

**Comment by jpittis** [comment]
Here's the link: https://github.com/Shopify/toxiproxy/releases/download/v2.0.0/toxiproxy_2.0.0_amd64.deb
I'll update the docs.

**Comment by gaorlov** [comment]
That did it. Thanks a ton!

**Comment by jpittis** [comment]
Our pleasure. :)
