### ISSUE TITLE
Alternative to current Node client

### ISSUE THREAD

**Issue by ihsw** [Shopify/toxiproxy#108]
The current Node client is out of date and it doesn't have any tests, and I have made a Node client compatible with toxiproxy-2.0 and it has tests.

I have made it out of necessity for my personal use and as an educational task in authoring a Node package written in TypeScript.

https://github.com/ihsw/toxiproxy-node-client

https://www.npmjs.com/package/toxiproxy-node-client

What are your thoughts on switching the docs to mention mine?

**Comment by Sirupsen** [comment]
@ihsw 👍

**Comment by Sirupsen** [comment]
I'd prefer to use one that's actually used as part of a test suite for real applications, in real companies. The previous one seemed to be an exercise, like this one, but out of date and doesn't seems to have been touched in a while.

**Comment by ihsw** [comment]
I do plan on using it for testing fault tolerance in my more serious projects.

**Comment by Sirupsen** [comment]
OK, go ahead and switch it in a PR.

**Comment by jpittis** [comment]
@ihsw: Any progress on this?

**Comment by ihsw** [comment]
@jpittis Progress on what? Not sure what you are referring to.

**Comment by jpittis** [comment]
For whatever reason I didn't notice that your node client was added to the README in https://github.com/Shopify/toxiproxy/pull/109. :)
