### ISSUE TITLE
better CLI error handling

### ISSUE THREAD

**Issue by jpittis** [Shopify/toxiproxy#113]
https://github.com/Shopify/toxiproxy/pull/112 updates our CLI library to a newer version with better error handling. We should figure out how this error handling works and change `toxiAction` to support the new error handling if it's a cleaner solution.

`toxiAction` should be updated to look something like this.

``` go
type toxiAction func(*cli.Context, *toxiproxy.Client) error

return func(c *cli.Context) error {
    return f(c, t)
}
```

And then all the action error handling should be ported to the new API.

**Comment by xthexder** [comment]
Toxiproxy 2.1.0 has been released.
