### ISSUE TITLE
Support for cluster of toxiproxy nodes

### ISSUE THREAD

**Issue by nytins** [Shopify/toxiproxy#115]
It would be nice if we can setup a cluster of toxiproxy nodes so that can use a load balancer to balance loads between these nodes. This avoids a single point of failure.

If a toxic is configured in any of the nodes, it should propagate to all nodes in the cluster automatically.

Want to check if this feature looks interesting with everyone.

**Comment by Sirupsen** [comment]
Curious, what's your use-case for load-balancing? Reliability? Are you running it in production?

**Comment by nytins** [comment]
We use it during our load testing and endurance testing. The endurance tests run for more than 12hrs. So if the toxiproxy node fails the whole test will need to be restarted.

**Comment by Sirupsen** [comment]
@nytins oh, interesting. Do you have backtraces on any of the failures?

Have you considered running a Toxiproxy node on each of the boxes talking to other servers, rather than treating them as load balancers?

**Comment by nytins** [comment]
We started using toxiproxy recently. So we haven't had any failures so far.

We deploy our REST API application as a docker image across multiple AWS instances. All these apps are configured to use a single toxiproxy load balancer endpoint. 

The toxiproxy stack consists of 1 load balancer and multiple nodes where toxiproxy installed.

We thought having a separate toxiproxy stack was a cleaner solution. And also all these stacks are created using terraform scripts so any other team can create these stacks just by running those scripts.

**Comment by Sirupsen** [comment]
I'm not completely understanding your architecture. Do you think you can draw it out?

What I'm trying to propose is that you don't put Toxiproxy on a host you don't have to communicate with anyway. For example, if your network path to talk to a service is:

```
REST service -> LB -> Toxiproxy -> REST service
```

With this setup (which from my understanding is what you're running) has the problem that, indeed, Toxiproxy is an extra part of the network path that could fail. So you want redundancy. If instead you put it somewhere on your network path that you'll have to access regardless, you won't have introduced any new reliability problems:

```
REST service -> LB -> Toxiproxy, REST service on the same box 
```

Sorry, I'm acting on very little information. Just trying to understand and suggest :-)

**Comment by nytins** [comment]
The stack that we use for load testing is
```
REST service -> LB -> Toxiproxy -> LB -> Mock REST service
```
We can run the Toxiproxy in the Mock service boxes itself as you suggested.
```
REST service -> LB -> Toxiproxy and Mock REST service on the same box
```
But still, if there are 5 nodes, there will be 5 Toxiproxy instances running in each node.
And if we need to configure these Toxiproxy instances, we will have to configure separately in each of those 5 nodes.

**Comment by Sirupsen** [comment]
Why do you need to run 5 Toxiproxy instances on each node? Why can't you just have 5 proxies in one Toxiproxy instance on each node?

**Comment by nytins** [comment]
I think I didn't explain properly. What I meant was there will be one Toxiproxy instance in each node. See the diagram below. There are 3 nodes and there are 3 Toxiproxy instances each of these instances will need to be configured separately.

![untitled diagram](https://cloud.githubusercontent.com/assets/8001559/16960811/f1335812-4db8-11e6-8555-9d5a8403f5ef.png)

**Comment by Sirupsen** [comment]
Ah, I understand. Why not put Toxiproxy on the same node as the REST service?

**Comment by nytins** [comment]
The REST service is again a cluster. I just showed a single box for simplicity. But actually its like below:

![toxiproxy2](https://cloud.githubusercontent.com/assets/8001559/16963239/78ea3a3c-4dc3-11e6-8c4a-18c8d0fcb9dc.png)

**Comment by Sirupsen** [comment]
Ah, I see now. Is it so bad that you have to do an HTTP request to multiple Toxiproxy instances to take things down? I don't think it's worth supporting this in Toxiproxy core. Another alternative is to script your load balancers to talk to all of the Toxiproxy instances automatically.

**Comment by nytins** [comment]
We won't be able to customize the LB because its Amazon Web Services Elastic LB service. 

But we might write a small utility which runs in all the nodes and polls toxiproxy for config changes. When there is any change, it will propagate to other nodes.

I think based on this discussion we can close this issue.

Thanks for the suggestions @Sirupsen

**Comment by Sirupsen** [comment]
@nytins enjoy the toxic!
