### ISSUE TITLE
Cant access toxiproxy server from outside host

### ISSUE THREAD

**Issue by nytins** [Shopify/toxiproxy#117]
I am not able to hit the toxiproxy server using the REST API for configuring proxies from outside of the host where it is running. 

`netstat -tulpn` shows that it is listening to the loopback address `127.0.0.1:8474`

For now as a workaround what I did was to create another proxy which listens on public ip and port 80 and forwards to `localhost:8474`

`PUBLIC_IP:80` --> `localhost:8474`

Wondering if anyone else faced this issue?

**Comment by Sirupsen** [comment]
Can't you just make it listen on the public IP, or `0.0.0.0`?

**Comment by nytins** [comment]
Apologies, I didn't realize the `toxiproxy-server` command has the configuration options.
Closing..
