### ISSUE TITLE
Unable to update toxic name and stream property

### ISSUE THREAD

**Issue by federicoorlandini** [Shopify/toxiproxy#120]
Hi,

I noticed that creating a proxy with a toxic and sending POST request to the URL http://localhost:8474/proxies/{proxyname}/toxics/{toxicname}, I cannot update the toxic name and the stream attribute.
Is this by design?

**Comment by Sirupsen** [comment]
Can you provide reproducible steps? Either through the CLI, API, a test case or `curl`.

**Comment by xthexder** [comment]
This is intended behaviour. A toxic's `name`, `type` and `stream` are all immutable since they're part of how toxics are keyed/referenced.
If you need you rename a toxic (though I'd be interested in hearing what the use case is?), you'll need to remove and recreate it with the new name.

**Comment by federicoorlandini** [comment]
Thank you for your feedback.
I have this use case because I'm working on this project: [](https://github.com/mdevilliers/Toxiproxy.Net), a .Net client for your ToxiProxy and I'm working on a test case in the test suite where I want to check that the toxic update feature is working, so I'm trying to update all the properties of an existing toxic.
