### ISSUE TITLE
Clarification of timeout toxic behavior

### ISSUE THREAD

**Issue by matez** [Shopify/toxiproxy#121]
Hey, according to the description of _timeout_ toxic it should stop all data *after* some specific timeout.

Let's say I have proxy _myproxy_ created
```
./toxiproxy-cli create myproxy --listen localhost:42666 --upstream google.com:80
```

And I create new toxic of _timeout_ type with 10s timeout
```
./toxiproxy-cli toxic add myproxy -n mytoxic --upstream --type timeout --attributes timeout=10000
```

Processing of simple http get request should take less then 10s so I assume toxiproxy shouldn't interfere in communication. But when I try it I get empty response after 10s. It works well without any toxic enabled.

```
date -R ; curl -vv localhost:42666 ; date -R        
Tue, 16 Aug 2016 15:58:32 +0200
* Rebuilt URL to: localhost:42666/
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 42666 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:42666
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
Tue, 16 Aug 2016 15:58:42 +0200

```

Am I doing something wrong or just don't understand well how it's supposed to work?

**Comment by Sirupsen** [comment]
@mataz Toxiproxy is doing the right thing, but perhaps the Timeout toxic is ill-named. The timeout Toxic is for triggering timeouts in the client, to ensure they work correctly. It won't send any data, ever. It will not pass any data through for x seconds, and then it will close the connection (what you see as `empty reply from server`).

If you have suggestions for how to make the documentation more clear, we'll happily accept a PR.

**Comment by matez** [comment]
@Sirupsen I see now. Thanks for explanation.
