### ISSUE TITLE
Simulate slow connection open

### ISSUE THREAD

**Issue by kevinhughes27** [Shopify/toxiproxy#123]
I'm trying to use Toxiproxy to test a connection that is slow to open (I am specifically trying to test our Elastic Search configuration which has both a request_timeout and a request open_timeout which is shorter https://github.com/Shopify/shopify-app-store/pull/1297). 

My test fails after the full timeout, not the open timeout (4 vs 2 seconds). From a discussion with @Sirupsen he pointed out that this is probably because when the Elastic Search client is routed through Toxiproxy the Toxiproxy server accepts the connection immediately and then applies the toxic. From the Elastic Search client's perspective, it passed the request open_timeout for this reason.

For discussion
@Sirupsen @xthexder @jpittis

**Comment by xthexder** [comment]
Unfortunately the way toxiproxy and TCP in general is set up, there's not a whole lot that can be done about this. If I remember correctly, when I tested this before, the kernel will accept / open the connection regardless of if `listener.Accept()` is called by the user.

Someone else might have some other ideas?

**Comment by kevinhughes27** [comment]
I kind of figured this might not be possible to do..

**Comment by Sirupsen** [comment]
If Toxiproxy because a L2 proxy it may be possible to delay the TCP opening handshake?

**Comment by xthexder** [comment]
This was brought up once before: https://github.com/Shopify/toxiproxy/issues/72

**Comment by xthexder** [comment]
Going to close this, since it's not really feasible and would pretty much require a rewrite. Maybe in the distant future.
