### ISSUE TITLE
cli: Allow host to be specified

### ISSUE THREAD

**Issue by dylanahsmith** [Shopify/toxiproxy#128]
At Shopify we use a VM to run services that a project depends on, including toxiproxy.  Unfortunately, toxiprox-cli is hard coded to use localhost.  That means that toxiproxy-cli can't be used from outside of the VM

I think there should be a global option to specify the host.  E.g. `toxiproxy-cli --host=example.com list`

**Comment by xthexder** [comment]
This should be easy to add, I'll throw together a PR.

**Comment by xthexder** [comment]
Toxiproxy 2.1.0 has been released.
