### ISSUE TITLE
Issues with re-routing https traffic

### ISSUE THREAD

**Issue by kvnavaneethan** [Shopify/toxiproxy#136]
Hi, 

I'm trying to setup a proxy for the https port 443. 
I've made the change such that the service in my VM runs on 488, and have used toxy-proxy cli to create a    proxy which runs on 443, and forwards it to 488. 

./toxiproxy-cli-linux-amd64 create Navaneethan --listen  localhost:443 --upstream localhost:488

The problem however is, I see a bunch of "source Terminated" messages on the toxy-proxy-server. 
Something like this. 

My question is, does toxy proxy support https traffic routing ? What am I missing. Is there any specific configuration change on the apache webserver that lets me route the https traffic ? 

Any help is appreciated. 

INFO[0016] Started proxy                                 name=Navaneethan proxy=16.125.74.114:443 upstream=ci-0050569a4a60.vse.rdlabs.hpecorp.net:488
INFO[0018] Accepted client                               client=16.78.175.17:39824 name=Navaneethan proxy=16.125.74.114:443 upstream=ci-0050569a4a60.vse.rdlabs.hpecorp.net:488
WARN[0018] Source terminated                             bytes=517 err=read tcp 16.125.74.114:443->16.78.175.17:39824: use of closed network connection name=Navaneethan
INFO[0018] Accepted client                               client=16.78.175.17:39825 name=Navaneethan proxy=16.125.74.114:443 upstream=ci-0050569a4a60.vse.rdlabs.hpecorp.net:488
WARN[0018] Source terminated                             bytes=178 err=read tcp 16.125.74.114:443->16.78.175.17:39825: use of closed network connection name=Navaneethan
INFO[0020] Accepted client                               client=16.78.175.17:39826 name=Navaneethan proxy=16.125.74.114:443 upstream=ci-0050569a4a60.vse.rdlabs.hpecorp.net:488
INFO[0020] Accepted client                               client=16.78.175.17:39827 name=Navaneethan proxy=16.125.74.114:443 upstream=ci-0050569a4a60.vse.rdlabs.hpecorp.net:488
INFO[0020] Accepted client                               client=16.78.175.17:39828 name=Navaneethan proxy=16.125.74.114:443 upstream=ci-0050569a4a60.vse.rdlabs.hpecorp.net:488
WARN[0020] Source terminated                             bytes=517 err=read tcp 16.125.74.114:443->16.78.175.17:39827: use of closed network connection name=Navaneethan
WARN[0020] Source terminated                             bytes=517 err=read tcp 16.125.74.114:443->16.78.175.17:39826: use of closed network connection name=Navaneethan
INFO[0020] Accepted client                               client=16.78.175.17:39829 name=Navaneethan proxy=16.125.74.114:443 upstream=ci-0050569a4a60.vse.rdlabs.hpecorp.net:488
INFO[0020] Accepted client                               client=16.78.175.17:39830 name=Navaneethan proxy=16.125.74.114:443 upstream=ci-0050569a4a60.vse.rdlabs.hpecorp.net:488
INFO[0020] Accepted client                               client=16.78.175.17:39831 name=Navaneethan proxy=16.125.74.114:443 upstream=ci-0050569a4a60.vse.rdlabs.hpecorp.net:488

**Comment by xthexder** [comment]
What you're doing should work fine. The log messages are all expected, though maybe they could be changed to be a little less worrying.

Basically what the logs are saying is that a client is connecting to the server, and then the server is closing the connection, which is expected with HTTP after requests are finished.
In the logs you posted, data is getting through to the server (517 bytes), so assuming your https client is working, you should have no issues.

If you're getting errors in your browser or app when trying to connect to https, then you can post that and I can see if I can help.

**Comment by kvnavaneethan** [comment]
Thanks for responding. 

I try to run the following curl command, and it returns couldn't connect to host (7) error. 
Which , I think means, it wasn't able to connect to the proxy that was set up for port 443. 

curl -k -X GET -H "X-Api-Version:300" -H "auth:LTQxNzQxMjQ4MDU0HyBcwZcNgCoxbvoYY093KrbiBlaJhyTe" -H "Content-Type: application/json" -H "Accept: application/json"  https://localhost/rest/server-hardware/32363636-3138-5355-4533-313833354C53
curl: (7) couldn't connect to host

**Comment by xthexder** [comment]
Https works fine for me:
```
# toxiproxy-cli c -l :443 -u google.com:443 google
Created new proxy google
# curl -k -H "Host: google.com" https://localhost/
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="https://www.google.ca/?gfe_rd=cr&amp;ei=47sHWPvGKoaN8QfM-ZOQCw">here</A>.
</BODY></HTML>
```

Can you try `netstat -l` and check to see if the proxy is actually listening on the port?
`toxiproxy-cli inspect` might also be useful to see if the proxy is created properly.
