### ISSUE TITLE
docker image no longer updating?

### ISSUE THREAD

**Issue by Dieterbe** [Shopify/toxiproxy#137]
Hello,
toxiproxy looks like a neat project. looking forward to play with it.
on https://hub.docker.com/r/shopify/toxiproxy/tags/ i see that the last image push was 6 months ago, whereas https://github.com/Shopify/toxiproxy/blob/master/Dockerfile was updated less than 2 months ago
also the current latest image has nothing in /go/bin, and no toxiproxy-cli binary anywhere:

```
root@toxiproxy:/go# find / -name toxiproxy-cli
root@toxiproxy:/go# ls -alh bin/
total 8.0K
drwxrwxrwx 2 root root 4.0K Oct 24  2015 .
drwxrwxrwx 4 root root 4.0K Oct 24  2015 ..
root@toxiproxy:/go# 
```

looking forward to have new images that have the toxiproxy-cli binary included. thanks

**Comment by Dieterbe** [comment]
looks like the cli binaries exist here:
```
root@toxiproxy:/go# find / -name '*toxiproxy-cli*'
/app/src/github.com/Shopify/toxiproxy/tmp/build/toxiproxy-cli-darwin-amd64
/app/src/github.com/Shopify/toxiproxy/tmp/build/toxiproxy-cli-windows-amd64.exe
/app/src/github.com/Shopify/toxiproxy/tmp/build/toxiproxy-cli-linux-amd64
```

**Comment by xthexder** [comment]
I looks like the docker image is still the latest version (2.0.0), but was just missing the cli binary.
I guess we missed the image update because there wasn't an actual version number update with it.

Should be able to upload a new docker image in a little bit.

**Comment by xthexder** [comment]
The docker image should be updated now as `2.0.0b` with the cli included.
