### ISSUE TITLE
toxiproxy-cli hangs in docker connecting to local toxproxy (related to internet?)

### ISSUE THREAD

**Issue by Dieterbe** [Shopify/toxiproxy#138]
hello!
new toxiproxy user here, trying out my first toxic steps.
I run it in docker, using the latest image that was just pushed today.
just 1 proxy and 1 backend, very light load.

i noticed that toxiproxy-cli, which worked fine first to add a proxy and a toxic, on subsequest commands started hanging. i ctrl-c'd the commands after they hung for minutes (the last 3 commands).

interesting to mention: around the same time my internet connection also became slow and started timing out.  while everything is local in a dockerstack entirely on my laptop, maybe my internet has something to do with it? has anyone experienced something like this before?

```
root@toxiproxy:/app/src/github.com/Shopify/toxiproxy# toxiproxy-cli inspect cassandra
Name: cassandra Listen: [::]:9042       Upstream: cassandra:9042
======================================================================
Upstream toxics:
Proxy has no Upstream toxics enabled.

Downstream toxics:
latency_downstream: type=latency stream=downstream toxicity=1.00 attributes=[ jitter=500 latency=1000 ]

Hint: add a toxic with `toxiproxy-cli toxic add`
root@toxiproxy:/app/src/github.com/Shopify/toxiproxy# toxiproxy-cli toxic delete cassandra -n latency_downstream:
Failed to remove toxic: RemoveToxic: HTTP 404: toxic not found
root@toxiproxy:/app/src/github.com/Shopify/toxiproxy# toxiproxy-cli toxic delete cassandra -n latency_downstream 
^C
root@toxiproxy:/app/src/github.com/Shopify/toxiproxy# toxiproxy-cli toxic delete cassandra -n latency_downstream
^C
root@toxiproxy:/app/src/github.com/Shopify/toxiproxy# toxiproxy-cli list                                         
^C

```

**Comment by xthexder** [comment]
This is definitely some strange behavior. It looks like the toxic removal failed in a bad way and hung the api.

My first question would be what does `cassandra:9042` resolve to? If it's on the same machine, Docker has some weird networking and I don't think you can use the same port in different containers unless you change some settings.

If it happens to be connecting to itself, this is undefined behavior, and I would expect it to crash from the feedback loop.

As for the external connection, that shouldn't affect the api in any way, it's.*supposed* to be isolated.

I'll have to play around with the docker container and see if I can reproduce this in any way.

**Comment by Dieterbe** [comment]
i have a cassandra container on the same machine (all containers run on my laptop) with hostname cassandra and the toxiproxy has a docker link `cassandra:cassandra`. as for resolving that's a bit hard to verify since the toxiproxy container doesn't have any tools like nslookup, but for a while the proxy seemed to be functioning just fine so it seems like the cassandra:9042 backend just worked.  it's definitely a different container so toxiproxy should not connect to itself.

thanks!

**Comment by xthexder** [comment]
Well, if you do end up able to reproduce it, try killing the toxiproxy server with `kill -SIGABRT <pid>`. It should output the stack traces and we'll be able to see where it's getting stuck.

**Comment by Dieterbe** [comment]
it looks like the problem was not the failed removal, because now it's working fine and the cli and api are very snappy

```
root@toxiproxy:/app/src/github.com/Shopify/toxiproxy# toxiproxy-cli toxic delete cassandra -n latency_down
Failed to remove toxic: RemoveToxic: HTTP 404: toxic not found
root@toxiproxy:/app/src/github.com/Shopify/toxiproxy# toxiproxy-cli toxic delete cassandra -n latency_downstream:
Failed to remove toxic: RemoveToxic: HTTP 404: toxic not found
root@toxiproxy:/app/src/github.com/Shopify/toxiproxy# toxiproxy-cli toxic delete cassandra -n latency_downstream 
Removed toxic 'latency_downstream' on proxy 'cassandra'
root@toxiproxy:/app/src/github.com/Shopify/toxiproxy# 
root@toxiproxy:/app/src/github.com/Shopify/toxiproxy# toxiproxy-cli toxic delete cassandra -n latency_downstream
Failed to remove toxic: RemoveToxic: HTTP 404: toxic not found
root@toxiproxy:/app/src/github.com/Shopify/toxiproxy# toxiproxy-cli toxic delete cassandra -n latency_downstream
Failed to remove toxic: RemoveToxic: HTTP 404: toxic not found
root@toxiproxy:/app/src/github.com/Shopify/toxiproxy# toxiproxy-cli toxic delete cassandra -n latency_downstream
Failed to remove toxic: RemoveToxic: HTTP 404: toxic not found
root@toxiproxy:/app/src/github.com/Shopify/toxiproxy# toxiproxy-cli list          
Listen          Upstream        Name    Enabled Toxics
======================================================================
[::]:9042       cassandra:9042  cassandra       true    None

Hint: inspect toxics with `toxiproxy-cli inspect <proxyName>`
root@toxiproxy:/app/src/github.com/Shopify/toxiproxy# 
```

**Comment by xthexder** [comment]
I'm really not sure what the cause initially was, it may have just been some weird things going on with the docker container networking.
If it happens again, you can the stack trace to help debug more and post it here, but for now I'll consider this closed.

**Comment by Dieterbe** [comment]
Ok thank you

**Comment by squarism** [comment]
I had this same issue when trying to proxy to a docker service.  Any connections would hang until I passed a new command to toxiproxy.  For example, my real use case is the redis example from the README but like a `get bacon` would hang until I did a `toxiproxy-cli toxic add -n downstream_redis_latency -d -t latency -a latency=500 slow_redis` or some other command that would jog toxiproxy.

It was very odd.  I just stopped using docker services temporarily (mac) and used redis from homebrew.  ❔ Mysterious.

**Comment by xthexder** [comment]
It's possible this could be an issue with older Go versions and MacOS Sierra since 2.0 was built with go 1.6.2
I'm currently updating my mac so I can test this and possibly push an updated build

**Comment by squarism** [comment]
It could also be how I'm doing docker networking since I have a few `docker network` configs.  I'm looking at that now.  I also wonder if combining the toxiproxy image with my redis image into a docker-compose bundle that is linked would get around this.

I'm also going to try inside a Linux vm with native docker.

**Comment by squarism** [comment]
I've tested on linux with native docker and it works fine.  Just to be clear what the problem and set up is:

```
homebrew redis listens on 6380

toxiproxy config is
toxiproxy-cli create slowredis -l localhost:6379 -u localhost:6380
toxiproxy-cli toxic add -n upstream_latency -t latency -a latency=500 slowredis
```
This is very similar to the README example.  So then you `redis-cli` to 6379 through toxiproxy.  That works.  Then replace the above config with a dockerized redis on mac and it fails in a very strange way: _it hangs until you poke toxiproxy_ (change the latency, do anything config change), then the request will go through.

Docker on Linux works fine.
```
# 16.04 vm
$ apt-get install docker.io
# add yourself to the docker group and re-login

# run the redis official image in the foreground
docker run --rm --name dockerized-redis -p 6380:6380 redis --port 6380
[redis is now listening on 6380]
[use the above toxiproxy config to forward 6379->6380 and slow it down by .5 seconds]

Test it!
redis-cli
127.0.0.1:6379> set bacon delicious
OK
(0.50s)

127.0.0.1:6379> get bacon
"delicious"
(0.50s)
```
So you can see it works fine under Linux with native docker.

Btw, I love how redis takes 500ms every time because of the toxiproxy config.  🌻  Toxiproxy is fun sometimes.

**Comment by xthexder** [comment]
I've been trying to debug this, but I can't seem to reproduce it on my mac.
What exactly is your network configuration? Are you running `toxiproxy-cli` from inside the container, or are you connecting from outside.
Any issues I had were related to the docker containers being in a VM, so I was doing everything from other containers rather than the host.

My original thought was that this was a `< go1.7` bug, but the latest docker container (2.0.0b) was built with go 1.7, and seems to work fine on my machine.

**Comment by xthexder** [comment]
I'm not sure if this will have an effect on the issue you're seeing, but are you still seeing the issue with Toxiproxy 2.1.0?
The new built is with go1.7.3 which had fixes for Sierra (though this might not be related if you were seeing it with the 2.0.0b docker container)

**Comment by squarism** [comment]
I was running docker services with "on the metal" toxiproxy `2.0.0` from homebrew.  So homebrew toxiproxy would talk to dockerized redis.  The docker image sha was `3ff093b50539` but I don't think I ever ran the cli or the server through the docker image.  I was thinking about it as to network the two images up.

**Update** I just brew upgraded to 2.1.0 and I can connect.  Idk what was up before.  I even did a `homebrew switch` to go back to 2.0.0.  Couldn't reproduce.  Really strange.  Idk, sorry.

**Comment by xthexder** [comment]
I believe the 2.0.0 version on homebrew was built with go1.6, which had issues with Sierra. I'm going to assume this was the cause, since 2.1.0 is built with go1.7 which has fixes in place.
