### ISSUE TITLE
chat room?

### ISSUE THREAD

**Issue by Dieterbe** [Shopify/toxiproxy#147]
Have you considered creating a chat room for this project or do you think it would be too low traffic to be worthwhile?
I certainly have a few questions that would get ironed out much quicker - and some ideas for the project - if there was a chat where developers and users could unite.

thanks,
Dieter

**Comment by xthexder** [comment]
I've created the IRC channel #toxiproxy on freenode, you're welcome to join. Not sure how much use it will get, but I'll stick around and see what happens with it.

**Comment by Dieterbe** [comment]
we should probably mention it in the readme somewhere so people can find it.

**Comment by casperisfine** [comment]
README was updated, closing.
