### ISSUE TITLE
macOS Sierra issue

### ISSUE THREAD

**Issue by odlp** [Shopify/toxiproxy#150]
After creating a new proxy and adding a latency toxic:

```sh
toxiproxy-cli create postgres --listen 127.0.0.1:5434 --upstream 127.0.0.1:5432
toxiproxy add postgres --type latency --toxicName latency --attributes latency=10 --downstream
```

Trying to establish a connection via PSQL never succeeds:

```sh
psql -d postgres://127.0.0.1:5434/postgres?sslmode=disable
```

However, connecting directly on port 5432 (not via toxiproxy) continues to work fine.

This is affecting a machine running macOS 10.12.1. The setup detailed above with toxiproxy works fine on OSX El Capitan 10.11.6.

Any help debugging this would be most appreciated!

---

Version information:
- toxiproxy-cli version 2.0.0 (installed via Homebrew)
- psql (PostgreSQL) 9.5.5

**Comment by xthexder** [comment]
I just upgraded to macOS Sierra myself and gave this a try.
Using the toxiproxy version from homebrew and postgres 9.6.1 from homebrew as well, I can't seem to reproduce this.
Are you getting any logs in the `toxiproxy-server` ?
You should be seeing something similar to this:

```
$ toxiproxy-server
INFO[0000] API HTTP server starting                      host=localhost port=8474 version=2.0.0
INFO[0035] Started proxy                                 name=postgres proxy=127.0.0.1:5434 upstream=127.0.0.1:5432
INFO[0130] Accepted client                               client=127.0.0.1:51856 name=postgres proxy=127.0.0.1:5434 upstream=127.0.0.1:5432
```

(Sorry for the delay in responding to this, it's been a busy couple weeks at Shopify)

**Comment by xthexder** [comment]
Can you try this again with Toxiproxy 2.1.0?
The new release was built with go1.7.3, so it should fix the issues with macOS Sierra

**Comment by odlp** [comment]
Sorry I hadn't replied sooner @xldenis - I didn't have access to another machine with MacOS Sierra until now.

I can confirm this is now working fine. Thank you for looking into it.
