### ISSUE TITLE
Dockerfile not port forwarding

### ISSUE THREAD

**Issue by jacobbednarz** [Shopify/toxiproxy#151]
Hello there! 👋 

I'm currently running this within our CI system and noticed that accessing the HTTP API doesn't work unless I explicitly forward 8474 to 8474 inside the container (usually via `-p 8474:8474`).

I'm unsure if this is a bug or you handle this differently in your setup? My setup looks like this:

```
docker pull shopify/toxiproxy
docker run -it -d -p 8474:8474 shopify/toxiproxy

# create HTTP requests for proxies and toxics
# run rspec
```

Interested to hear your thoughts on this one but if it is a bug I'll gladly open a PR to get it fixed.

**Comment by sirupsen** [comment]
We just `--net=host` I believe.

**Comment by xthexder** [comment]
The current Dockerfile already has the port defined: https://github.com/Shopify/toxiproxy/blob/master/Dockerfile#L8
There's no way to actually make it forward with default arguments though.
What you want is the `-P` argument, which will forward all the ports defined in the Dockerfile.

**Comment by jacobbednarz** [comment]
> We just --net=host I believe.

This doesn't seem to forward any ports for me but I could be very well missing something here.

```
$ docker run -it -d --net=host shopify/toxiproxy
660a2f7b01d63b3f915fbed12e27d20c623e4d9f219ee411ee27f9d3b8994f0d

$ docker ps
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS              PORTS                  NAMES
660a2f7b01d6        shopify/toxiproxy                "/app/toxiproxy -host"   2 seconds ago       Up 1 seconds                               adoring_ramanujan
```

> What you want is the -P argument, which will forward all the ports defined in the Dockerfile.

The problem with using this is that it ends up giving a random port which might a PITA to manage in your tests if you need to reference it. 

```
$ docker run -it -d -P shopify/toxiproxy
fbe6cad094cc5672f7d4d75561dea6317b303073bc4d3466861d3936bdfb3205

$ docker ps
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS              PORTS                     NAMES
fbe6cad094cc        shopify/toxiproxy                "/app/toxiproxy -host"   3 seconds ago       Up 1 seconds        0.0.0.0:32768->8474/tcp   sick_fermi
```

I think to make this slightly easier for out of the box usage, we could update the documentation to include `-p 8474:8474` (which I feel would solve my concerns from above).

**Comment by sirupsen** [comment]
`--net=host` assumes that all other containers are in the same networking namespace (i.e. they're run with `--net=host`) or that you don't run other tests in a networking namespace (e.g. not in a container).
