### ISSUE TITLE
add an option to  return 400 and 500 reponse codes

### ISSUE THREAD

**Issue by attachmentgenie** [Shopify/toxiproxy#160]
I would like to be able to simulate a service that occasionally  returns a error state instead of the expected response. 

When providing this toxi as a percentage of all requests we can dial this up or down to see how the application responds to the responsive yet utterly broken downstream.

**Comment by customcoops77** [comment]
Nice if I could do it.

**Comment by customcoops77** [comment]
I don't understand it and I'm sad my heart is breaking .  Wish I knew how to change my life fast.

**Comment by attachmentgenie** [comment]
closing in favor of #50
