### ISSUE TITLE
Add a config file example

### ISSUE THREAD

**Issue by robsonpeixoto** [Shopify/toxiproxy#163]
The current document are missing a config file example. Please add one.

**Comment by boly38** [comment]
while waiting for doc (agree that is missing :) ),

 I just add here one sample found from https://github.com/Shopify/toxiproxy/issues/217

Seems that listen hostname must match "-host" parameter
please note that I'm not toxiproxy contributor (only end-user)
```
cat config/proxies.json
[
  {
    "name": "id_dev_http",
    "listen": "0.0.0.0:26080",
    "upstream": "id"
  }
]
```

**Comment by alexgvo** [comment]
Somebody know, can you add & assign toxics on proxies during startup of server? Using proxies.json?

**Comment by boly38** [comment]
(I've not done the test but ) @alexgvo did you try something similar to this sample (embedding toxics definiton) ?

```
{
    "tservice": {
        "name": "tservice",
        "listen": "[::]:9000",
        "upstream": "servicehost:8080",
        "enabled": true,
        "toxics": [
            {
                "attributes": {
                    "timeout": 0
                },
                "name": "serviceTimeout",
                "type": "timeout",
                "stream": "upstream",
                "toxicity": 1
            }
        ]
    },
    "tother": {
        "name": "tother",
        "listen": "[::]:9100",
        "upstream": "otherservice:8081",
        "enabled": true,
        "toxics": []
    }
}
```

**Comment by boly38** [comment]
ok sorry then :|
NB/ `8474` is already toxiproxy default port

**Comment by jpittis** [comment]
If you ping me on a PR to update the docs, it should be a quick turnaround to merge.

**Comment by KernelDeimos** [comment]
If anyone else finds this on Google like I did let me save you some time - **adding toxics like this doesn't work right now**.

- #447 describes where in the code toxics are excluded
- [this PR](https://github.com/gitpod-io/gitpod/pull/14473) vaguely describes a solution maybe I think
