### ISSUE TITLE
CI is failing

### ISSUE THREAD

**Issue by jpittis** [Shopify/toxiproxy#166]
I'm getting CI failures with the following error:
<img width="828" alt="screen shot 2017-03-19 at 6 25 53 pm" src="https://cloud.githubusercontent.com/assets/5767836/24085385/8fa1fc88-0cd1-11e7-986d-df881e7f9e56.png">

**Comment by sirupsen** [comment]
Our `circle.yml` may not work anymore, although that error sounds incredibly strange if it appears consistently. Perhaps it's for one of our dependencies?

If you find it easier to switch to Travis altogether in lieu of getting Circle to work, that's completely fine with me!

Thanks for taking a stab at this.

**Comment by jpittis** [comment]
This was a permissions issue. CI is now working.
