### ISSUE TITLE
cli fails with https hosts

### ISSUE THREAD

**Issue by mmollaverdi** [Shopify/toxiproxy#174]
```
toxiproxy-cli --host https://my-toxyproxy-host.com create toxi_name -l localhost:8000 -u my-upstream-host
Failed to create proxy: Post http://https//my-toxyproxy-host.com/proxies: dial tcp: lookup https: no such host
```

For some reason, the `--host` value is appended with `http://` (`http://https//my-toxyproxy-host.com`). It works fine if it already starts with `http://` though.

**Comment by jpittis** [comment]
Hey there! Thanks for reporting the issue.

Unrelated to the issue, the Toxiproxy HTTP API does not support HTTPS.
