### ISSUE TITLE
Fix logrus import

### ISSUE THREAD

**Issue by domano** [Shopify/toxiproxy#179]
The upper case import github.com/Sirupsen/logrus is breaking builds at our project.

case-insensitive import collision: "github.com/Sirupsen/logrus" and "github.com/sirupsen/logrus"

It should be changed to the lowercase import "github.com/sirupsen/logrus"

Not doing a Merge Request because i do not know about other dependencies in your projects.

Does it build for you with the current master of logrus?

**Comment by jpittis** [comment]
Fixed with #183
