### ISSUE TITLE
toxiproxy Server should exit with code 0 when SIGTERM'd

### ISSUE THREAD

**Issue by dlmiddlecote** [Shopify/toxiproxy#180]
Currently, when toxiproxy Server receives a SIGTERM signal (from `docker stop` say) it exits with a non-zero code. 

Is this desired, or a feature? Could this be changed by handling a SIGTERM and exiting with 0?

**Comment by jpittis** [comment]
I wouldn't say this is high priority but if this feature could be added without too much complexity, I can't think of why it wouldn't be appreciated.

**Comment by dlmiddlecote** [comment]
I'll do this.

**Comment by jpittis** [comment]
Thanks @dlmiddlecote <3
