### ISSUE TITLE
Can Toxiproxy be used to inject toxics to Postgres DB connection ?

### ISSUE THREAD

**Issue by du-premraj** [Shopify/toxiproxy#186]
Can you help me to understand whether the toxiproxy can be used to add toxics to postgres DB connection by listening at standard postgres port and forwarding the connection to an upstream port where the postgres is listening ?

**Comment by jpittis** [comment]
That sounds like a perfect use case for Toxiproxy.

I would recommend reading how Toxiproxy works in the README and then following the [cli example](https://github.com/Shopify/toxiproxy#cli-example).

**Comment by du-premraj** [comment]
Thank you
