### ISSUE TITLE
Query on Concurrency

### ISSUE THREAD

**Issue by du-premraj** [Shopify/toxiproxy#193]
Can you please help me to clarify the below query ?

1. I have created a proxy for a connection and applied latency toxic to it.
2. Suppose client A connects to server A through that proxy and latency is getting applied in upstream direction. 
3. At the same time another client B is sending request to same server A via same proxy. 

Will the second connection request be blocked until the first connection request completes ? I meant the second connection from client B to Server A will be allowed only after the first connection request from Client A to server A is successfully out of the delay injected by latency toxic ?

**Comment by jpittis** [comment]
The second connection will not block. Connections through a single proxy are performed in parallel and latency is applied separately to each connection.

```
A sends                                               A arrives
| connection A normal latency | added latency by proxy |
               B sends                                               B arrives
               | connection B normal latency | added latency by proxy |
```

This behaviour is meant to simulate a slow network. You can assume it will behave the same way.

Thanks for your question. 😄

**Comment by du-premraj** [comment]
Thanks a lot
