### ISSUE TITLE
Trying to simulating at/near endpoint, any feedback is appreciated

### ISSUE THREAD

**Issue by someburner** [Shopify/toxiproxy#196]
Ive looked through the issues regarding this (like #39), and understand it's probably outside of scope, but nonetheless I'm pretty hooked on this idea and I think it would be extremely helpful for trying to simulate the absolute worst network conditions- the ones on the customer's side. Particularly socket connections, but could be an interesting spin on http too I suppose, full explanation of what I'm after is at the bottom.

**TL;DR:** Having trouble getting bridged packets to go into the `localhost:1883` proxy. It might be 100% due to router configuration, but I want to know if there is any reason why they shouldn't be just in the code first before investigating further.

---

Wall of text for my setup/why other projects won't work, AFAIK...

In #39 @jpittis pointed out it would be a fairly big overhaul to do layer 3, so this is not a feature request or issue per-say. Quick tangent on that- I do wonder if some code could be grafted from dockers [networking](github.com/docker/libnetwork/) lib for the layer 3 question in general. I have no idea if that would help in my scenario but something to consider for others perhaps.

The main issue I'm having is that every single other project pretty much uses **netem**, and if they don't, then they are lacking the desired features that netem has, like latency. And I can't use netem because I need to simulate LAN congestion-- which is easy to do on a laptop with `hostapd`, and a 4.x kernel core i7. But my goal is to be as close to an average users' setup as possible, with a secondary mission of hooking this all up to CI, so it's not a long term solution.

I should note this is for testing MQTT (websocket), so it definitely is important which end the delay occurs at for simulating. The idea is: use the nice toxiproxy rest APIs to run through tests and observe how WiFi connected devices react to various filters/stress tests/etc.

And here's where I'm at:

I'm part-way there on an AC-RT3200. Cross-compiled the project Go sources with a project called `entware-ng`. And I actually got it going immediately, delays/filters and all, *but only on `localhost`*. That is, if I set listen to 0/0 and uplink to our remote server, it will work, but I can't get packets to go into the listening port (ie- from the `wlan` interface "into" `localhost`). But if I ssh into the router and do a `pub` or `sub` (like redis) from there, things are peachy. So after a day.. or 3.. of messing around with kernel settings/router interface settings, I am a bit stuck. 

Part of the issue is that it's actually not trivial to forward/feed traffic form a router's WiFi interface into the toxiproxy drain. One reason is that the kernel by default considers external pkts going to 0.0.0.0 to be martians. But I think I found a parameter to at least not drop them, but I still cant get them to go in.

Another issue is the internal port mappings. That one was not too hard though. What I've done is simply reserved the `1883` and `51883` on the router, set the uplink to **51883** for toxi, then run [xinetd](https://github.com/xinetd-org/xinetd) with this configuration.

```sh
# service options for xinet.d/mqttfwd
{
	disable 	= no
	socket_type 	= stream
	type 		= UNLISTED
	wait 		= no
	user 		= root
	bind 		= 127.0.0.1
	port 		= 51883
	redirect 	= 1.2.3.4 1883       ## my remote server
}
```
which runs as a daemon. And then fire up toxiproxy with

```
# create toxi with uplink to 51883
tpcli c mq0 -l 0.0.0.0:1883 -u 127.0.0.1:51883
```

So how it works is:

* `xinet` handles the 51883<-->remote:1883 link
* And `toxiproxy` uplink is going to `51883`
* So as far as other services on the router are concerned, if we have traffic to/from `localhost:1883`, it *does* get 'toxified'.

Ive tested both up+down filters and it does have the intended results, but only for traffic originating from `localhost` whereas I need the WiFi traffic going in there..

I suppose it makes sense, since you need to still redirect the WiFi packets to `localhost` (or `lo`?) from their original destination of `1.2.3.4`.... but that is where `iptables` and fiends come in and for the life of me I cannot get that to work. I found a parameter for allowing you to bind to external IPs (aka *not* `127.0.0.1`, like the bridged `wlan` in this case), and that allows me to run the `cli create` instead of it getting an error, but also had no affect. So I'm starting to think it's just due to the nature of the ip stack.

With iptables, if I set up `FORWARD` routes it skips over userspace and goes straight out my `WAN` to the server. And if I don't, I get nothing. Again, I think that might be do to some trickery in the kernel somewhere, or not configured quite right on routes, but I'm hoping maybe there's another way.

Lastly, I'll mention I did get intercepting via `toxiproxy` on a 2nd remote server with some success, but then you are introducing some funky/unreliable stuff into your test network which I'm uncomfortable with, since then I will be testing/debugging firmware for a configuration that is different than what customers see.

So I suppose I just wanted to see if anyone has tried this, has any ideas or suggestions, or if I'm completely missing some easier/better way. The other issue is, this was the first I've ever used Go, normally being C/Cpp/Python, but I'm more just worried about spending a huge amount of time if there's a different way about it.

**Comment by someburner** [comment]
Closing, no longer stumpted :) 

Turns out rebuilding the kernel with `netem` wasn't as hard to do as I thought.

**Comment by jpittis** [comment]
Glad you found a solution! :)
