### ISSUE TITLE
Simple question with ToxiProxy Http API

### ISSUE THREAD

**Issue by ffogell** [Shopify/toxiproxy#197]
Hey ! How are you ?

I downloaded the windows version : toxiproxy-server-windows-amd64.exe

I installed it on a VM and I want to connect to it and add proxy using the c# client.
When I tried connecting using the client I get a {"No connection could be made because the target machine actively refused it 10.130.145.184:8474"}

While doing netstat -oa 

I see : TCP    127.0.0.1:8474

So that mean I can only access the server using locahost, our plan was to host the toxiproxy server on a vm and re-use it.   It there a way to access the server http api from outside the machine ? (When I test it locally everything works => client and server on the same machine)

Well I'm kinda a noob with all this stuff (and still learning) so any insight would be appreciated :)

tyvm !

**Comment by ffogell** [comment]
I figured it out that I need to compile it and pass appropriate values.

**Comment by jpittis** [comment]
You should be able to change which host Toxiproxy listens on by using the `host` flag and `port` flag when starting the server.

For example if you wanted to listen on `0.0.0.0:5555`, you could use the following command to start Toxiproxy.

```
./toxiproxy-server --host 0.0.0.0 --port 5555
```

Thanks for your question.
