### ISSUE TITLE
Failed to create proxy: Post http://localhost:8474/proxies: dial tcp [::1]:8474: getsockopt: connection refused

### ISSUE THREAD

**Issue by LucasMaliszewski** [Shopify/toxiproxy#200]
Followed the install directions, toxiproxy-cli displays the manual but when running 

`toxiproxy-cli create redis -l localhost:26379 -u localhost:6379 
`
I'm receiving

> Failed to create proxy: Post http://localhost:8474/proxies: dial tcp [::1]:8474: getsockopt: connection refused

I'm not entirely sure where to start with this. I'm running OS X HS v10.13.3 and Redis locally installed via brew on port 6379. I'm intending to use this for Shopify, but I'm using the guide with the Redis examples.

**Comment by jpittis** [comment]
The client is getting a `connection refused` error when attempting to tell the `toxiproxy-server` to create a new proxy. Are you sure you're running `toxiproxy-server`? The simplest way to accomplish that would be to open a separate terminal and run `./toxiproxy-server`.

**Comment by LucasMaliszewski** [comment]
@jpittis So it sounds like the server is either not running or unable to access it. I'll go back and review the guide and see what I missed. Thanks for the response!

**Comment by jpittis** [comment]
Feel free to open this again if you're still having trouble. Especially if you do start the server and still get an error like this. Thanks Lucas.
