### ISSUE TITLE
Fix cli help example for specifying several attributes for toxic

### ISSUE THREAD

**Issue by gavvvr** [Shopify/toxiproxy#202]
> toxiproxy-cli h t

gives me an incorrect example for adding new toxic:

> toxic add:
>   usage: toxiproxy-cli add <proxyName> --type <toxicType> --toxicName <toxicName> \
>   --attribute <key=value> --upstream --downstream
> 
>   example: toxiproxy-cli toxic add myProxy -t latency -n myToxic -a latency=100,jitter=50

This leads to:
> Failed to add toxic: AddToxic: HTTP 409: toxic already exists

Correct usage will be (as said in #139):
> toxiproxy-cli toxic add myProxy -t latency -n myToxic -a latency=100 -a jitter=50

**Comment by miry** [comment]
It seems fixed:

```shell
$ toxiproxy-cli h t
...
     toxic add:
       usage: toxiproxy-cli toxic add --type <toxicType> [--downstream|--upstream] \
               --toxicName <toxicName> [--toxicity <float>] \
               --attribute <key=value> [--attribute <key2=value2>] <proxyName>
   
   
       example: toxiproxy-cli toxic add -t latency -n myToxic -a latency=100 -a jitter=50 myProxy
```
