### ISSUE TITLE
toxiproxy-server hangs when starting (macOS Sierra)

### ISSUE THREAD

**Issue by ajwalters** [Shopify/toxiproxy#203]
I'm having problems starting toxiproxy-server.  When i fire it up, it just hangs on "API HTTP server starting"

Are there any logs that I can get a little more insight as to what is going on to debug?

toxiproxy 2.1.2 installed via Homebrew on macOS Sierra 10.12.6

Thanks

**Comment by jpittis** [comment]
Would you start toxiproxy-server in one terminal window.

```
$ ./toxiproxy-server
```

In another window would you run and show the output of

```
$ ./toxiproxy-cli list
```

**Comment by ajwalters** [comment]
Closing this.  Perhaps restarting my machine helped because the exact same create command works now.  Thanks

**Comment by jpittis** [comment]
Thanks for opening an issue @ajwalters
