### ISSUE TITLE
server start hanging on MacOS Sierra

### ISSUE THREAD

**Issue by fantapop** [Shopify/toxiproxy#207]
I saw this in another bug.  I'm not sure if its the same thing.  I can't get this running on my mac:

It just hangs here:
```
$ docker run -P --rm -it --net=host shopify/toxiproxy
INFO[0000] API HTTP server starting                      host=0.0.0.0 port=8474 version=2.1.3
```

I've tried different ports

I've also tried installing it via brew and the same behavior happens outside of the container.

**Comment by xthexder** [comment]
By default Toxiproxy runs as a foreground app. Are you able to connect to it by opening a separate terminal?

Assuming that works as expected, you can run the docker container in detached mode:
https://docs.docker.com/engine/reference/run/#detached-vs-foreground

**Comment by fantapop** [comment]
When you say connect to it do you mean connect to the http server?
When running via docker and it stops as I indicated above, it doesn't connect.

When installing 2.1.2 via brew, I get the same output however there is an http server running on 8474.  In that case I get a 404 when requesting the root.

I did just try toxiproxy-cli create and that action caused another line to be printed out of the foregrounded toxiproxy-server which says:
```
INFO[0112] Started proxy                                 name=devint-rtmp proxy=127.0.0.1:1935 upstream=<redacted server name>:1935
```

I'll try to run the container in the background and see how it does.

**Comment by fantapop** [comment]
Okay, I see what's going on here.  The http server is running however it never prints http server started.  The next time it prints a message is when the first client connects.

Previously when I tried to connect I hadn't mapped the server to port 8474 so toxiproxy-cli couldn't it.  It works if I do this:

```
docker run -p8474:8474 --rm -it shopify/toxiproxy
```

The brew version also works.  I was expecting to be able to visit the root of the http server in a browser and see a visual representation of the existing proxies.

It might be clearer to print something after the http server is started.
