### ISSUE TITLE
Toxicity field can not be altered

### ISSUE THREAD

**Issue by alexxsanchezm** [Shopify/toxiproxy#214]
By adding toxics to my current proxi configuration the `toxicity` can not be altered. Probably I'm doing something wrong but there is no output log that explain my mistake.
I ran this:
`toxiproxy-cli toxic add yvt_app_android toxicity '0.25' -t slow_close -a delay=2500 -d`
and this:
`toxiproxy-cli toxic add yvt_app_android toxicity 0.25 -t slow_close -a delay=2500 -d`
and this:
`toxiproxy-cli toxic add yvt_app_android toxicity=0.25 -t slow_close -a delay=2500 -d`
 But when I run the `toxicity-cli inspect yvt_app_android` the toxicity hasn't changed.

toxicity version 2.1.3

**Comment by xthexder** [comment]
I think you want `-toxicity 0.25` or `-tox 0.25`
Also, if a toxic already exists and you want to change it, you'll want to use `toxiproxy-cli toxic update yvt_app_android -toxicity 0.25 -n toxic_name`
