### ISSUE TITLE
I can't recv data from server

### ISSUE THREAD

**Issue by Grapefruit-Shu** [Shopify/toxiproxy#225]
Mobile phone connected to my own agent ,and my own agent connects to the game server.But i use toxiproxy between my own agent and game server, it can analog network delay.but i can't revc data from game server the mobile phone can revc the data.
the code：
![image](https://user-images.githubusercontent.com/34914897/44521918-67083180-a707-11e8-8c35-976ac15360aa.png)

**Comment by jpittis** [comment]
Hey @Grapefruit-Shu. It's quite difficult to debug your issue with the minimal information and explanation you've provided. I'd recommend having a look at the README again to understand the details of how Toxiproxy works and behaves.
