### ISSUE TITLE
Install on RHEL7

### ISSUE THREAD

**Issue by gauravnitc243** [Shopify/toxiproxy#226]
I am trying to install toxiproxy 2.1.3 using 'toxiproxy-server-linux-amd64' on rhel7 but server is not coming up. I just ran the file over shell, it does give message saying 'starting toxiproxy server' but it never comes up. Are there any additional steps involved?

**Comment by jpittis** [comment]
Hey there.

Just to confirm you're running the right commands, this is how I would try out Toxiproxy to see if it's working:

From one shell, run the following:

````bash
$ toxiproxy-server
INFO[0000] API HTTP server starting                      host=localhost port=8474 version=git-fe6bf4f
````

From another we curl the server and ensure it's returning a valid HTTP response. (In this case a 404.)

````bash
$ curl localhost:8474
404 page not found
````

Would you be able to post the shell output of you starting Toxiproxy and the method that you're using to decide whether "it never comes up"?

**Comment by xthexder** [comment]
I've noticed there's been some confusion around this in the past, and it might be worthwhile making a change to the log message.
Right now there is only a "server starting" message, and no "server started" message. Either adding the second message, or just moving the existing message to after server start might help with people's confusion.

**Comment by gauravnitc243** [comment]
I got confused with 404 page not found message. Now I got it, I tried with different endpoint now, http://localhost:8474/version, it is returning correct version.

Thanks for pointing this out. This issue can be closed. If logger message can be improved then that will  remove confusion as mentioned in above post.

**Comment by gauravnitc243** [comment]
Issue can be closed.
