### ISSUE TITLE
Unable to specify port for cli

### ISSUE THREAD

**Issue by ashiyen** [Shopify/toxiproxy#250]
I can specify a port for the server but not for the cli. So if the toxiproxy server is running on a different port, then I cannot get to cli using the http interface because the cli code seems to be hardcoded for 8474, unless I am missing something

**Comment by jpittis** [comment]
The [host](https://github.com/Shopify/toxiproxy/blob/master/cli/cli.go#L199-L202) flag should be usable for this. `-h 127.0.0.1:1337` for example.

**Comment by ashiyen** [comment]
Thanks, Jake.

So the -h should be specified while running the cli? For example we are trying toxiproxy-cli  create myproxy --listen 0.0.0.0:9052 --upstream 10.5.23.120:9052 and we tried the -h at multiple locations and it didn't work

Or should the -h be used while starting the server itself?

**Comment by senthilkumar-s** [comment]
to add on to @ashiyen comment, we got toxiproxy-server started as toxiproxy-server --host 0.0.0.0 --port 8080
and the following works - curl http://localhost:8080/proxies

Now how to invoke the toxiproxy-cli referring the toxiproxy-server thats listening on 8080 ?

Thanks

**Comment by jpittis** [comment]
Seems to be working for me:

```
$ toxiproxy-cli --h "http://127.0.0.1:1234" list
Failed to retrieve proxies: Get http://127.0.0.1:1234/proxies: dial tcp 127.0.0.1:1234: getsockopt: connection refused
```

**Comment by miry** [comment]
There is an example https://github.com/Shopify/toxiproxy/blob/26f2a85bd75698427dac087860068c973ff647fa/bin/e2e#L34
how the toxiproxy client with `--host` flag.

The `--host "http://toxiproxy:port"`  is a global option of the toxiproxy client it goes before any command.
