### ISSUE TITLE
Installing toxiproxy in RHEL 7

### ISSUE THREAD

**Issue by shyamnayak6** [Shopify/toxiproxy#268]
Hi,
I would like to install toxiproxy in RHEL 7.7 version and downloaded toxiproxy-server-linux-amd64
 from 2.1.4 release.

Could you please share the installation or execution steps for the same.

Need one more clarification like go should be installed for this or not ?

Thanks,
Shyam

**Comment by mc2zp** [comment]
Try to install Golang on your system (1.12+), git clone this repo and preform 'make build' on it.
