### ISSUE TITLE
arm binaries

### ISSUE THREAD

**Issue by beac0n** [Shopify/toxiproxy#269]
There are binaries for the client and server software on https://github.com/Shopify/toxiproxy/releases

However, there are no binaries for the arm platform.
Would it be possible to add binaries for the arm platform?

**Comment by miry** [comment]
I see the plus to release ARM for MacOS M1 arch as well. Do you think someone can contribute and send PR?

**Comment by jclusso** [comment]
I can try, but I really don't know much about this. I'll give a look and see if maybe I can figure something out.

**Comment by miry** [comment]
Created https://github.com/Shopify/toxiproxy/pull/300 waiting for review. Next step release a new version.

**Comment by jclusso** [comment]
Will this fix Homebrew also or is this just to get docker working? Just curious.

**Comment by miry** [comment]
It would be a next step. There is https://github.com/Shopify/toxiproxy/pull/295 exists that release multiple arch docker image.

**Comment by miry** [comment]
fixed in https://github.com/Shopify/toxiproxy/pull/301
