### ISSUE TITLE
Unable to create proxy using toxiproxy-cli

### ISSUE THREAD

**Issue by santiagocardin** [Shopify/toxiproxy#307]
Using toxiproxi-cli v2.1.5 the _listen_ argument seems to be ignored when creating a proxy:

```
$ toxiproxy-cli create datagrid --listen 127.0.0.1:11222 --upstream datagrid-hotrod:11222
NAME:
   toxiproxy-cli.exe create - create a new proxy
  usage: 'toxiproxy-cli create <proxyName> --listen <addr> --upstream <addr>'


USAGE:
   toxiproxy-cli.exe create [command options] [arguments...]

OPTIONS:
   --listen value, -l value    proxy will listen on this address
   --upstream value, -u value  proxy will forward to this address
   --help                      show help (default: false)

Required argument 'listen' was empty.
```
The same command works fine with toxiproxy-cli v2.1.4

**Comment by miry** [comment]
@santiagocardin Try as workaround:

```
toxiproxy-cli create --listen 127.0.0.1:11222 --upstream datagrid-hotrod:11222 datagrid
```

I believe it came from some optparser upgrades.

**Comment by miry** [comment]
It is related to the library that used: https://github.com/urfave/cli/blob/master/docs/migrate-v1-to-v2.md#flags-before-args
Now Flags should go before the arguments.
I am going to update the documentation.

**Comment by miry** [comment]
Created a PR: https://github.com/Shopify/toxiproxy/pull/308

**Comment by miry** [comment]
@santiagocardin Can we close the issue?

**Comment by santiagocardin** [comment]
Working again using the suggested order of parameters, thanks!
