### ISSUE TITLE
toxiproxy-cli: Required argument 'type' was empty

### ISSUE THREAD

**Issue by arouel** [Shopify/toxiproxy#324]
When using `toxiproxy-cli`, I always get `Required argument 'type' was empty` despite the type is set.

# Steps to reproduce

1. `toxiproxy-cli create -l localhost:8088 -u localhost:8080 myproxy`
2. `toxiproxy-cli toxic add myproxy -t latency -a latency=1000`
  - the command terminates with `Required argument 'type' was empty` (same result when using `--type`)

# Environment

1. macOS 10.15.7
2. installed via Homebrew as descibed in the README.md
2. toxiproxy-cli version 2.1.5

**Comment by miry** [comment]
closing the issue. feel free to recreate if there is still any problem
