### ISSUE TITLE
Go API

### ISSUE THREAD

**Issue by Sirupsen** [Shopify/toxiproxy#34]
We should have a Go API for `toxiproxy`. It wouldn't be hard to test, as it's essentially what's already in `api_test.go`, it just needs to be in a sub package that can be imported independently of the Toxiproxy daeamon.

**Comment by xthexder** [comment]
I can hammer this out next week, unless someone else is interested in doing it sooner.

**Comment by Sirupsen** [comment]
@wvanbergen ^

**Comment by wvanbergen** [comment]
:+1: nice - we want this for https://github.com/Shopify/sarama

**Comment by Sirupsen** [comment]
That's exactly why I opened the ticket :-)

**Comment by Sirupsen** [comment]
Started the work here https://github.com/Shopify/toxiproxy/pull/35

**Comment by Sirupsen** [comment]
#35 is now in master. This has a simple client that can add and remove proxies, which is enough for basic resiliency testing. I'll work on implementing a wrapper for toxics next.

**Comment by xthexder** [comment]
Looks like this issue can be closed now?
