### ISSUE TITLE
Docker container log level

### ISSUE THREAD

**Issue by PatrickDuncan** [Shopify/toxiproxy#343]
Hello, how do we change the log level of the Docker container? It defaults to `info`, I'd like to change it to `warning` or `error`. I don't see any mention of it with a shallow search.
I'm hoping there's an env var we can use.

**Comment by miry** [comment]
@PatrickDuncan I want to clarify, you want to change the log level for toxiproxy server via env variable. I have fastly checked the code and could not find anything to do it.
