### ISSUE TITLE
Proxies reappear after deleting them

### ISSUE THREAD

**Issue by Roman-Sht** [Shopify/toxiproxy#344]
I send delete requests for proxies using the API. I get a success 204 response and I see that the proxies do not appear anymore.
But, sometimes, when I check after a few more seconds, the proxies reappear.

Toxiproxy version: 2.1.4

**Comment by miry** [comment]
@Roman-Sht Can you test with latest version? 

It would easy to me to debug the problem if you provide exactly how did you run server, how did you send API request and after what time it was appeared again.
