### ISSUE TITLE
Simplify by always using ProxyWithToxics

### ISSUE THREAD

**Issue by Sirupsen** [Shopify/toxiproxy#36]
Is there any reason why the `Proxy` type doesn't just have `Toxics` always? It's perfectly fine for them to be nil. I also think proxies should be returned with toxics in all cases in the API. This simplifies things a great deal.

@xthexder thoughts?

**Comment by xthexder** [comment]
The main reason was that listing toxics and proxies locks up certain parts of the code until the request finishes. Looking back at it, I don't think this actually affects the data flowing through the proxies, just other api calls.

I think it would be fine to always include the toxics in api responses. We can replace the `/proxies` endpoint with what is currently `/toxics`.

**Comment by Sirupsen** [comment]
yeah, that's what I was thinking :+1:
