### ISSUE TITLE
Unable to hook up Toxiproxy to Sql Server

### ISSUE THREAD

**Issue by airdrik** [Shopify/toxiproxy#363]
I've got a project that's currently set up to use testcontainers with an mssql container to verify certain database interactions.  I'm trying to set up toxiproxy in front of the database so I can test some of the database driver reactions.
Problem is that when I try connecting to the proxy address+port using either the jdbc driver or using the sqlcmd command line tool, it fails to connect.  
I've tested a few different setups with the same or similar results:
* testcontainer instances for both sql server (image: mssql/server:2019-latest) and toxiproxy
* testcontainer instance for sql server, non-container toxiproxy installed via homebrew
* non-container toxiproxy with proxy pointing at sql server running on one of our dev servers.

In the each case, I'm able to connect and execute queries from the command line using sqlcmd as follows:
`sqlcmd -S 'localhost:1433' -d database_name -U userName -P thePassword -Q "SELECT 1"`
(prints out the results of the query)
But when I try connecting to the proxy, configured as:
`toxiproxy-cli create test_db -l localhost:51433 -u localhost:1433`
I get the following:
`sqlcmd -S 'localhost:51433' -d database_name -U userName -P thePassword -Q "SELECT 1"`
`Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : TCP Provider: Error code 0x2726.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : A network-related or instance-specific error has occurred while estab
lishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..`

Any assistance is appreciated. Thank you.

**Comment by miry** [comment]
I believe it is related to SSL handshake. Try to disable SSL.

**Comment by miry** [comment]
Sorry could not help with MsSQL.
