### ISSUE TITLE
Change to IP proxy instead of TCP proxy

### ISSUE THREAD

**Issue by Sirupsen** [Shopify/toxiproxy#39]
It'd make sense for the proxy to be at layer 3, instead of layer 4. Means we can re-order packets, etc., and rely on the TCP implementation to provide the stream. It'd also make us able to support UDP, SCTP, etc.

@xthexder

**Comment by xthexder** [comment]
I think things like reordering packets are out of toxiproxy's scope. The end result would be that TCP reorders / resends them and you just get added latency at the client level, we're trying to test apps not TCP.

UDP support would be nice, but I'm not sure how useful it would be. Any critical data that's sent between apps would be sent over TCP, so there's less of a use case from a resiliency standpoint.

What I like about doing things above the TCP layer is we can make protocol aware toxics that do things like force a read/write to fail (i.e. the server is responding but still down).

**Comment by Sirupsen** [comment]
Fair point :)

**Comment by Dieterbe** [comment]
> UDP support would be nice, but I'm not sure how useful it would be. Any critical data that's sent between apps would be sent over TCP, so there's less of a use case from a resiliency standpoint.

FWIW i'm trying to use toxiproxy in between my apps' clustered instances, which use https://github.com/hashicorp/memberlist which uses UDP. So I think UDP would be very useful :)

**Comment by jpittis** [comment]
Creating a layer 3 proxy would be a real pain cause we'd probably have to mess around with TUN TAP interfaces. Turning Toxiproxy into a layer 3 proxy sounds like a huge rewrite and wouldn't easy.

**Comment by Dieterbe** [comment]
FWIW driven by my use case above i've been researching some toxiproxy alternatives, specifically for tools that target the network layer instead of the application layer and https://github.com/gaia-adm/pumba seems to be the most promising one

**Comment by jpittis** [comment]
A quick glance at pumba makes me that it's not cross platform because it relies on `tc`. (A linux specific tool.) Thanks for sharing that with us!

**Comment by petemounce** [comment]
UDP support would be _incredibly_ useful for testing computer-game networking code. For a detailed insight into "why UDP over TCP" for games, https://gafferongames.com/post/udp_vs_tcp/ does an excellent job.

**Comment by sirupsen** [comment]
Perhaps we could implement this without impacting the TCP layer? Instead have an IP-layer that works differently, with different toxics?

**Comment by jpittis** [comment]
It would be totally possible to add UDP support. A lot of the system may assume TCP and therefore be a lot of work to refactor.
