### ISSUE TITLE
Unable to create Proxies on PCF environment

### ISSUE THREAD

**Issue by AnuradhaBose** [Shopify/toxiproxy#403]
Hi,
I am trying to use ToxiProxy on PCF environment. I have deployed ToxiProxy and my application both on PCF environment. I have created a proxy to my app on port 8082. But when I try to hit the app endpoint using this proxy port, it is not able to connect. PCF does not provide a direct way of exposing ports, it is driven by routes. Is there any way to get this working on PCF?

**Comment by miry** [comment]
@AnuradhaBose I would like to help, but I have lack of knowledge about "PCF environment". 

- Can you share what does mean PCF environment?
- How can I reproduce the problem?

**Comment by AnuradhaBose** [comment]
Hi @miry - By PCF environment I mean, I have deployed the ToxiProxy and my app(pcfDemo) on Pivotal Cloud Foundry. The endpoint of my app is https://pcfDemo.pc.onefiserv.net:8083/pcftest/test. I have created a proxy using toxiproxy-cli create -l 0.0.0.0:8082 -u pcfDemo.pc.onefiserv.net:443 pcfProxy. But when I do this, curl -ivk -H "Host:pcfDemo.pc.onefiserv.net" https://toxiproxy.pc.onefiserv.net:8083/pcftest/test, I get an error saying connection refused.

**Comment by miry** [comment]
@AnuradhaBose Thank you for clarification. 
It is a known issue to support SSL handshake with different hostnames.

Similar:
- https://github.com/Shopify/toxiproxy/issues/267
- https://github.com/Shopify/toxiproxy/pull/270

**Comment by AnuradhaBose** [comment]
Hi @miry- Could you please let me know how the ToxiProxy server works internally? When we create a proxy for example on port 8082, does any process run on 8082? How does ToxiProxy identify a request and redirects it to the proxied host? I am trying several options for this to work on Pivotal Cloud Foundry, hence the ask for more details on how the server works.

**Comment by AnuradhaBose** [comment]
Hi @neufeldtech - Thanks for the detailed explanation. I have tried it in my local desktop and it seems to work fine. But it does not seem to work when I deploy it on Pivotal Cloud Foundry. I am able to start the toxiproxy server as an app in PCF. I am also able to create proxies to other apps on the same Pivotal Cloud Foundry environment. The proxy works when I ssh into the app container and run it using localhost. But when I try to access the proxy endpoint from outside( say postman) it does not work. Is there any way to resolve this ?

**Comment by miry** [comment]
@AnuradhaBose I would start to check logs from Pivotal and security rules to access some ports. Check logs in toxiproxy server.
