### ISSUE TITLE
Toxiproxy hangs indefinitely while removing toxicity

### ISSUE THREAD

**Issue by mikael-carlstedt** [Shopify/toxiproxy#412]
Toxiproxy-server version: 2.3.0

Symptoms:
* Toxiproxy API call to remove toxicity is hanging indefinitely waiting for the HTTP DELETE response
* Toxiproxy-cli is unresponsive

This is the exact API call sequence that often but now always triggers the toxiproxy server to hang:

```
    proxy.toxics().latency("latency", DOWNSTREAM, 6000).setJitter(0);
    // two minutes delay
    // The toxic added above is the only one for this proxy
    for (Toxic toxic : proxy.toxics().getAll()) {
      toxic.remove(); // The call that hangs
    }
```

There is a lot of TCP traffic over the proxy during the entire time (it's being used as a Kafka listener proxy in a load test scenario). The Toxiproxy log shows this warning for the proxy in question at the same second as the hanging call is initiated:
`Aug 25 19:15:56 us1tst-cnxms002.int.clxnetworks.net toxiproxy-server[1145]: time="2022-08-25T19:15:56Z" level=warning msg="Destination terminated" bytes=15693610 err="readfrom tcp 10.96.147.83:9094->10.96.140.179:39556: write tcp 10.96.147.83:9094->10.96.140.179:39556: write: broken pipe" name="10.96.147.83:9094_us1tst-cnxms002.int.clxnetworks.net"
`
That is a rather infrequent warning, occurring only a handful of times in the course of half an hour. I'm thinking it's too much of a coincidence not to be related to the hanging server. The server does however continue to log 'Accepted client' and 'Source terminated' after this (and even one more 'Destination terminated' fifteen minutes later).

**Comment by mikael-carlstedt** [comment]
Yes, it looks like exactly the same issue!

**Comment by miry** [comment]
Great. I am looking to it today.
Closing as duplication and you copy paste the description there.

**Comment by mikael-carlstedt** [comment]
The latency toxic in the code snippet above is the only toxic on this proxy (downstream, latency=6000, jitter= 0).
