### ISSUE TITLE
Reopen all the PRs that were closed unintentionally because of master -> main rename

### ISSUE THREAD

**Issue by jonatan-ivanov** [Shopify/toxiproxy#499]
By renaming `master` -> `main` I think you unintentionally closed lots of PRs, see: https://github.com/Shopify/toxiproxy/pulls?q=is%3Apr+is%3Aclosed+sort%3Aupdated-desc

(I think using the rename feature of GitHub would have prevented this.)
- [x] https://github.com/Shopify/toxiproxy/pull/211
- [x] https://github.com/Shopify/toxiproxy/pull/218
- [x] https://github.com/Shopify/toxiproxy/pull/215
- [x] https://github.com/Shopify/toxiproxy/pull/466
- [x] https://github.com/Shopify/toxiproxy/pull/451
- [x] https://github.com/Shopify/toxiproxy/pull/419
- [x] https://github.com/Shopify/toxiproxy/pull/284
- [x] https://github.com/Shopify/toxiproxy/pull/270
- [x] https://github.com/Shopify/toxiproxy/pull/195

**Comment by dianadevasia** [comment]
@jonatan-ivanov All the accidentally closed PRs have been reopened and rebased against the `main` branch which is the new default branch. 
Let me know if its good I can close the issue then.

**Comment by jonatan-ivanov** [comment]
@dianadevasia Thank you!
