### ISSUE TITLE
Tag and release v2.6.0?

### ISSUE THREAD

**Issue by dnwe** [Shopify/toxiproxy#520]
I saw that [2.6.0 milestone](https://github.com/Shopify/toxiproxy/issues/434) had sadly been closed, presumably because @miry's role at Shopify no longer involves toxiproxy.

However, it would be good if someone with maintainer rights could tag and release v2.6.0 — in particular b36799eeb54a72cf773ccd6cc0ad736be9a98ae5 fixed up some bodyclose issues in the client (where resp.Body wasn't closed) that causes a resource leak

**Comment by miry** [comment]
cc: @Shopify/resiliency

**Comment by abecevello** [comment]
I have shipped what was on the main branch as version 2.6.0: https://github.com/Shopify/toxiproxy/releases/tag/v2.6.0.
