### ISSUE TITLE
No docker image?

### ISSUE THREAD

**Issue by tuxinaut** [Shopify/toxiproxy#61]
It seems so that no docker image is available :exclamation: :question: 

```
tuxinaut::sm191 { ~/workspace } -> $ sudo docker pull shopify/toxiproxy
Pulling repository shopify/toxiproxy
FATA[0002] Tag latest not found in repository shopify/toxiproxy 
tuxinaut::sm191 { ~/workspace } -> $
```

**Comment by Sirupsen** [comment]
@tuxinaut argh, sorry about that—use `sirupsen/toxiproxy` for now. I'll try to push it today.

**Comment by tuxinaut** [comment]
No problem I'll use the mentioned docker image until you upload the image to the right account.

**Comment by Sirupsen** [comment]
The Docker image was already there, it just didn't have the `latest` tag which is the default. You can use the version `1.1.0`. I tried to push `latest` in https://github.com/Shopify/toxiproxy/commit/ce789316afd35f8fb659e1a5bec59966a546ed92 but for some reason it doesn't work.
