### ISSUE TITLE
Slow TCP Accept and Read cannot be simulated

### ISSUE THREAD

**Issue by xthexder** [Shopify/toxiproxy#72]
Currently a proxy will always accept new connections right away, so there is no way to test client connection timeouts (only `connection refused` when the proxy is disabled).

It is also not possible to test Write failures/timeouts since https://github.com/Shopify/toxiproxy/pull/67. All incoming data will be read in and buffered by toxiproxy right away, so TCP Writes can't fail on either the server or client.

**Comment by xthexder** [comment]
This issue is fixed with this commit: https://github.com/Shopify/toxiproxy/commit/9b92c503f4dcd05b03bc67642a003521cffafa1f
A backport isn't really feasible for < 2.0, so this issue will be closed with the 2.0 release.

**Comment by xthexder** [comment]
Fixed in 2.0
TCP Accept can't be simulated at the application level, so that isn't possible without iptables or kernel-level things.

**Comment by pushrax** [comment]
It's possible to use raw sockets to simulate a slow TCP handshake.
