### ISSUE TITLE
Integrate with `goproxy`

### ISSUE THREAD

**Issue by abourget** [Shopify/toxiproxy#90]
Have you taken a look at https://github.com/abourget/goproxy ? I'd really like to be able to integrate both toxiproxy and goproxy.. to be able to instrument a proxy for multiple purposes, and adding to the mix toxicity..

Do you think it'd be easy ?

**Comment by xthexder** [comment]
It would certainly be possible to put Toxiproxy infront of goproxy to get the functionality of both, but you would need to set up your own control code (you won't get the same sort of HTTP API for goproxy).
It could be possible to hook into the proxy logic of goproxy and implement it into a toxic, but I haven't spent too much time looking at how interface `net/http` with an existing connection.

**Comment by abourget** [comment]
to keep goproxy the main instrumented proxy (that handles _all_ calls, going out of an Android device or a Windows machine), I'd like to sprinkle some toxicity only for certain hosts, and I'd glue in some control APIs on the proxy to do so (or simply programmatically wire it in my compiled proxy).

To do that, I'd need toxiproxy to actually be on the receiving end .. perhaps implementing the RoundTripper interface simply.. does it do that currently ?
