### ISSUE TITLE
the deb package does not install any init.d file

### ISSUE THREAD

**Issue by allan-simon** [Shopify/toxiproxy#97]
The README mentions 

```
wget -O toxiproxy-1.2.1.deb https://github.com/Shopify/toxiproxy/releases/download/v1.2.1/toxiproxy_1.2.1_amd64.deb
$ sudo dpkg -i toxiproxy-1.2.1.deb
$ sudo service toxiproxy start
```

for ubuntu, however when installing it on a ubuntu 14.04 , I can't do the `service` start

**Comment by Sirupsen** [comment]
[The definition](https://github.com/Shopify/toxiproxy/blob/master/Makefile#L54) puts it in `/etc/init/toxiproxy.conf`—do you not see it there? Do you have the logs for `dpkg`?

**Comment by pushrax** [comment]
Note: it's only configured for upstart, are you by chance using systemd?

**Comment by allan-simon** [comment]
sorry, in order to test it, i was using the docker image "phusion/baseimage"  https://hub.docker.com/r/phusion/baseimage/  which is based on ubuntu14.04, and it seems they've replaced upstart by  http://smarden.org/runit/  which is expecting  "old-school" init.d script
